### ISSUE TITLE
Improve error reporting for bit-constraint based expression solving

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#107]
The function `AffineExpression::try_solve_through_constraints` should report why it was not able to solve an expression.

**Comment by leonardoalt** [comment]
@georgwiese do you know if this was done during your latest/current witgen refactoring?

**Comment by georgwiese** [comment]
I'm not doing anything there, but looking at [`try_solve_through_constraints `](https://github.com/powdr-labs/powdr/blob/main/executor/src/witgen/affine_expression.rs#L287-L340), it looks like this has been resolved. The reason can be one of:
- There is an unconstrained polynomial
- Range constraints are overlapping
- The expression is unsatisfiable (which is a hard error)
