### ISSUE TITLE
read_polys_file hangs if file is empty

### ISSUE THREAD

**Issue by leonardoalt** [powdr-labs/powdr#1155]
https://github.com/powdr-labs/powdr/blob/main/number/src/serialize.rs#L115

When the PIL file has no fixed columns (like https://github.com/powdr-labs/powdr/blob/main/test_data/asm/empty.asm), this function hangs while trying to read the file (which exists but it's empty).

Steps to reproduce:

```bash
cargo run pil test_data/asm/empty.asm -f -o output --field bn254
cargo run verification-key output/empty.pil --backend halo2 --field bn254 -d output
```

**Comment by pacheco** [comment]
fixed by #1156
