### ISSUE TITLE
Block machines

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#116]
Block machines can handle lookups in "state machines" of the following form:

- The lookup uses a query selector that has a fixed period (i.e. is 1 on each `k`th row, and zero otherwise).
- The values in the rows of the machine are reset based on this selector (they might be individually shifted +-1 row, though)

The way we handle the lookup is as follows:
- If the query can be satisfied directly (i.e. the values already exist), we return those values
- Otherwise, we create a new block of rows of length `k` at the end of the existing blocks, with the query row at the end of that block. We try to fill the rows in the machine by going back and forth across all `k` rows, each time working on a window of two rows, until we do not make progress anymore.

We need to modify the usual mechanism a little since we need to be able to go "backwards", i.e. infer values of `a` based on a known values of `a'`.

We should be able to solve the common binary arithmetic machine as follows:

One sweep from top to bottom should infer that the `a`, `b` and `c` columns are bit constrained (due to `a' = (1 - RESET) * a + freeA * FACTOR` - `freeA` is a single block (byte) and `FACTOR` is a simple shift).
Another sweep from bottom to top should infer the values of `freeA` and `a`.
The final sweep from top to bottom fills the `c` values based on the lookup in the fixed columns.

**Comment by leonardoalt** [comment]
What's missing here?

**Comment by chriseth** [comment]
We only check that the selector is periodic. But yeah, as long as we don't have any better way to implement a block machine, it's probably good enough. I'm not sure though, if this could lead to invalid or nondeterministic assignments.
Closing for now.
