### ISSUE TITLE
Rust Profiler

### ISSUE THREAD

**Issue by georgwiese** [powdr-labs/powdr#1174]
We should have a profiler for Rust code, generating a flame graph that shows how many rows in the execution trace we need for each function.

@chriseth implemented a prototype a while ago: #330

**Comment by leonardoalt** [comment]
I guess the profiler should be rather for powdr-asm?

**Comment by chriseth** [comment]
Yes, but based on rust functions which are stored as debug information inside the riscv assembly

**Comment by georgwiese** [comment]
@pacheco I think this is done, right?
