### ISSUE TITLE
Let statements turn into intermediate columns depending on explicit type

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#1190]
```rust
col x;
let y = x;
let z: expr = x;
```

In the above code, `z` is an intermediate column while `y` is not. The only difference is the explicit type.

I think this is a bug and the nature of the symbol should not change depending on if the type is given explicitly or not.

Either all of those are intermediate columns or none and e.g. only `col z = x` is an intermediate column.

**Comment by chriseth** [comment]
Another option suggested by @georgwiese is to make only `let x: col = x` intermediate columns. And then we extend the type checking to allow the following RHS for `col`-typed symbols:
`int -> fe`, `int -> int`, `expr`.

**Comment by georgwiese** [comment]
And another option would be to inline expressions and add another step that decomposes identities of too high degree. Then intermediate polynomials would not need to be explicit ever.

**Comment by chriseth** [comment]
I took another look at this because it gets important now (I don't want to clutter the stdlib with needless intermediate columns).

One problem is that again we need to distinguish PilStatement (i.e. stuff at statement level) and ExpressionStatement (the new stuff where `col x` is not available). One issue here is that the StatementProcessor that handles PilStatement needs to know if it is an intermediate column or not without the type checker, which only runs much later. This means that the Display function for Analyzed needs to generate strings that can be processed by the StatementProcessor. Maybe we'll remove that later, but that's how it is now.

Proposal:

```
// creates intermediate column or fixed column depending on the RHS.
// int -> int and int -> fe are fixed columns, expr is intermediate column.
let x: col = ...
// same here, expects an array on the rhs
let x: col[k] = ...

// Creates an intermediate column, this is printed from Analyzed
col x = ...;
// Creates an array of intermediate columns, this is printed from analyzed and it's actually new syntax.
col x[k] = ...;
```

So what needs to change?

- Display for Analyzed needs to be adjusted.
- statement_processor needs to be able to process `col x[k] = ...`.
- the condenser needs to handle definitions of intermediate columns in the form of `let x: col = ..`.
  Currently, those are always fixed columns, but it will be able to know the type, so it can differentiate.
