### ISSUE TITLE
ASM: Move latch and operation_id from machine declaration

### ISSUE THREAD

**Issue by leonardoalt** [powdr-labs/powdr#1251]
Currently a block machine is written like this:

```rust
machine Binary(latch, operation_id) {
    ...
    col witness operation_id;
    col fixed latch(i) { if (i % 4) == 3 { 1 } else { 0 } };
    ...
}
```

The idea is to remove them from the machine declaration and be an attribute, for example:

```rust
machine Binary {
    ...
    #[operation_id]
    col witness operation_id;
    
    #[latch]
    col fixed latch(i) { if (i % 4) == 3 { 1 } else { 0 } };

    ...
}
```

The reason for that is that we want to be able to pass shared machines to submachines, which would fit better a syntax that occupies that space:

```rust
machine Binary(mem: Memory) {
    ...
}
```

**Comment by chriseth** [comment]
I think adding a annotation mechanism could complicate the whole thing, and while the header might not be an ideal place to put the latch and op id, I could imagine something like the following, just because it is much easier to implement right now:
```
machine Binary(arg1: int, arg2: MachineSomething) with latch: latch, operation_id: operation_id {
  ...
}
```

**Comment by Schaeff** [comment]
What if instead of an annotation we could use a special stdlib/corelib function?

```
col witness operation_id;
std::link::operation_id(operation_id);
```

And later deriving that with `#[derive(operation_id)]`

**Comment by chriseth** [comment]
Can this be closed, @pacheco ?
