### ISSUE TITLE
PIL: Allow statements that evaluate to `()` and block expression that return nothing should return `()`

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#1309]
The following code should be valid at any context:
```
let f: int -> () = |i| {};
let g = |i| {
  f();
}
```

It essentially means that

1) the last component in a Block can be empty, which is the same as `()`.
2) if `e` evaluates to `()` the just `e;` at statement level is the same as `let _ = e;` (or in other words, the type `()` is valid for an expression at statement level)

and just because we are touching this area:

3) A block with just an expression is a valid block, i.e. the statement vector can be empty.

**Comment by chriseth** [comment]
All functions that return `constr[]` in the standard library but don't actually return something should be changed to return `()`

**Comment by gzanitti** [comment]
This block in the grammar seems to be the one represented by BracedExpression, but what about BlockExpression? Both should be unified?

https://github.com/powdr-labs/powdr/blob/9472671b9bb2f936c372fa98dbce381fda61c999/parser/src/powdr.lalrpop#L631

**Comment by chriseth** [comment]
Yes, I think so!

**Comment by gzanitti** [comment]
Hey Cris, I'm combining both expressions, but allowing the blocks to be empty generates a few shift-reduce conflicts.

The main problem is that there are several rules in the grammar with:

```
"{" <expressions:ExpressionList> “}”
```

for example:

```
SelectedExpressions: SelectedExpressions<Expression> = {
    <selector:Expression?> "{" <expressions:ExpressionList> "}" => SelectedExpressions{<>},
    Expression => SelectedExpressions{selector: None, expressions: vec![<>]},
}
```


and if I allow the blocks to be empty (or actually, if I allow it to have no statement at all), the parser doesn't know how to handle it:

```
BlockExpression: Box<Expression> = {
    "{" <stmts:StatementInsideBlock*> <expr:BoxedExpression?> "}" => Box::new(Expression::BlockExpression(stmts, expr))
}
```


How do you think we should approach it? I don't see that they can be combined, so I guess we would have to differentiate them in the grammar with some special token or something maybe? What do you think?

**Comment by chriseth** [comment]
Ah right, the SelectedExpressions are quite annoying and will give us headaches for some other things as well (for example structs). So maybe we should change that syntax? It will break compatibility with polygon-pil, but I guess that is fine.

What about `a * [x, y]`? Then a lookup would look like `a * [x, y] in b * [v, w]`.

I think this could work with the grammar. It would still be a special case with the type checker because the `Mul` trait will not be able to have different types, but I think it's still a step forward.
