### ISSUE TITLE
Store and replay trace of how witnesses are generated.

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#133]
In the block machine, we more or less try different rows one after the other and generate witnesses from that in multiple iterations. This is quite time-consuming since we need to evaluate all identities on all rows until we find something new.

Instead, we could (depending on the known column input values) record which new witness got generated how from what information. On the next run, we can replay this trace on the new input values and generate all witnesses in one go without needing to search through the rows. In the end, this could be close to manually generating the witnesses.

Of course, we need to make sure that we are not missing any constraints that could make special new values invalid. We could also just do one last run of validation once we have the witnesses. Or just do it at the very end - in the end, the witnesses are forced to have these values and if they violate a constraint, something is very much off anyway.

**Comment by chriseth** [comment]
It might actually be sufficient for the block machine to record which identity lead to process on what row in which order. We can do the same for the main machine. There, at least for VM operation, the order of identities strongly depends on the value of PC. So we could somehow record that the PC lookup always makes progress and depending on which instructions are assigned, other identities make sense to look at first. The question is how to make this generic.

**Comment by leonardoalt** [comment]
@Schaeff do you think this is still needed/relevant in powdr2?

**Comment by leonardoalt** [comment]
I think some of this was done? @georgwiese @chriseth

**Comment by georgwiese** [comment]
Yes, I'd say this is what the sequence cache is doing.
