### ISSUE TITLE
Documentation inconsistency - Rust subcommand 

### ISSUE THREAD

**Issue by aminlatifi** [powdr-labs/powdr#1387]
Changed happend in the commit 101829b23075f20aeb8e1883dcc3a4bfb547891c caused this command to not be executable anymore
https://github.com/powdr-labs/powdr/blob/cbc5dd118e0098fc21b65569fc834715c7ccc9a5/riscv/tests/riscv_data/vec_median/src/lib.rs#L11

**Comment by onurinanc** [comment]
You can run the vec_median test as follows:

First, compile it using powdr-rs

`cargo run -r --bin powdr-rs compile riscv/tests/riscv_data/vec_median -o tmp`

Then, you can give the input to the asm file using `powdr-rs execute` as follows:

`cargo run -r --bin powdr-rs execute tmp/vec_median.asm -i 5,11,15,75,6,5,1,4,7,3,2,9,2`
