### ISSUE TITLE
Odd analyzed output for public inputs

### ISSUE THREAD

**Issue by Schaeff** [powdr-labs/powdr#1458]
When analysing a pil file with public inputs, we end up with two namespaces, one of them with an empty name. Is this the desired behaviour? cc @chriseth 

Input:
```
namespace Air(2);
    col witness y;
    public out = y(1);
```

Command:
```
cargo run pil air.pil
```

Output
```
namespace Air(2);
    col witness y;
namespace (2);
public out = Air.y(1);
```

**Comment by Schaeff** [comment]
Related: public declarations with the same name in different namespaces conflict:
```
namespace Air0(2);
    col witness y;
    public out = y(1);
namespace Air1(2);
    col witness y;
    public out = y(1);
```

yields

```
namespace Air0(2);
    col witness y;
namespace (2);
public out = Air1.y(1);
namespace Air1(2);
    col witness y;
namespace (2);
public out = Air1.y(1);
```

Notice how `out` is defined twice as `Air1.y(1)`

**Comment by chriseth** [comment]
Yes, due to polygon compatibility publics have no namespace and need to be globally unique. I have no problem with relaxing that and treating them the same way as columns.

**Comment by Schaeff** [comment]
Got it, thank you!
