### ISSUE TITLE
Witness generation trace for main machine

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#157]
This issue is an adaptation of https://github.com/chriseth/powdr/issues/133 for the main machine.
In the main machine, the order in which witnesses are generated from which identities is not always the same.
If it is an assembly machine, it strongly depends on the value of the pc.

We could still try to record and replay traces, but also record deviations from previously recorded traces. This creates trees (or DAGs) of traces. The tricky part is to find out what the branch conditions in deviations are.

We could also not have any branch conditions, and just try all successors of a node that were previously recorded. If none of them work, we try all the other identities. This should still be much faster than trying all possible identities.

------------------------------
Implementation notes:

In the main machine, assign IDs to identities and lookup machines.
Create a new component, the ProcessingSequenceOracle.

In the struct:
```
oracle: ProcessingSequenceOracle
```

In compute_next_row:
```
oracle.new_row();
while let Some(identity) = oracle.next() {
  // process identity
  // if successful:
  oracle.identity_successful(identity);
  // if failed:
  oracle.identity_failed(identity)
}
```

The oracle works as follows:
Initially, `next()` just iterates through all identities.

It has internal structures:
- successful: set of successful calls in the current row
- failed: set of failed calls in the current row
- cache: map of sets of successful calls to vector of next identities to try
- offset: current offset inside that vector

`next()`:
 - if cache does not have an entry for successful or if "offset" is beyond the vector length, try the next identity that is neither successful nor failed
 - otherwise, try the vector element at offset and incement offset

`identity_successful(identity)`:
- add the identity to  `cache[successful]`
- add the identity to `successful`

`identity_failed(identity)`:
- add the identity to `failed`

**Comment by chriseth** [comment]
The DAG approach is probably not that useful. What could be useful is to analyze constraints and see if it contains "triggers", i.e. boolean-constrained variables who will enable assignments:

`(1 - X) * ...` has `X = 0` as a trigger. So whenever `X` is assigned `0`, we take a look at this identity.
We can go a step further and see if we have all information required to fully analyze that identity.

What probably also has a very high impact is checking if lookups are "ready to be processed". This of course depends on the lookup, but I think we waste a lot of time querying a lookup with only partial information.

**Comment by chriseth** [comment]
During traversal, it might be sufficient to dynamically return from AffineExpression which witness columns could produce a new result (depending on the operation) and then maybe store them in a bit mask.

**Comment by leonardoalt** [comment]
@Schaeff how does this relate to powdr2?

**Comment by leonardoalt** [comment]
I guess this is done.
