### ISSUE TITLE
Dynamic VADCOP

### ISSUE THREAD

**Issue by georgwiese** [powdr-labs/powdr#1572]
See a prototype here: #1558

We already have "static" VADCOP: Machines can have different sizes, known at compile time. We should allow the prover to chose the size at run-time, which enables them to only pay for what they need.

This requires the following steps:
- [x] #1496 
- [ ] The linker needs to be changed so that it keeps machines with a degree of `None` (which means that it can have any size)
- [x] #1570 
- [x] Implementation in `CompositeBackend`: It should create the proof using the fixed columns chosen at runtime, and store the selected size with the proof. Then, in the verification, the verifier can select the correct fixed column commitments from the verification key
- [x] Witgen needs to be adjusted to chose a suitable size for each machine

**Comment by georgwiese** [comment]
> The linker needs to be changed so that it keeps machines with a degree of `None` (which means that it can have any size)

I'm still not 100% clear if this is the correct approach. It would be a breaking change: Most of our STD machines don't have a degree set, and there is currently no way to pass it from the instantiating machine. So you could only create proofs using the `CompositeBackend` after this change.

**Comment by Schaeff** [comment]
One approach which would work for now and is not a big change is the following. 

Machines have an optional minimum degree (as opposed to degree now). Then the linker should take a boolean composite flag as a parameter. The objects have an optional minimum degree and an optional degree. 

If the composite flag is off, the linker sets all degrees to that of main and errors out if the degree is smaller than any of the minimum degrees. 

If the composite flag is on, the linker forwards the minimum degrees and sets the degrees to None.

**Comment by georgwiese** [comment]
Sounds like you're proposing two things:
1. The `composite` linker flag sounds like the same I proposed in the last paragraph?
2. Also introduce a minimum degree

Do we need (2)? I think all machines will either have a fixed size or work with any size.

**Comment by Schaeff** [comment]
If we don't have (2), for machines of fixed size, in the monolithic setting, would we just overwrite the degree to that of main? What if the fixed columns are defined with the original fixed length, how would we extend them? Does it always work to copy a previous row? With a minimum degree, we get that information from the user.

**Comment by georgwiese** [comment]
Yeah, good points!

What if a machine could set the degree of the machines it instantiates, overriding any existing value? Then, for a monolithic proof, we would just set all sizes to be the same; for static VADCOP, we'd set them to whatever size we want; and for dynamic VADCOP, we would leave them set to `None` for machines that can have a variable size.

We could also add an assertion that you can't overwrite the degree with a smaller value.

**Comment by georgwiese** [comment]
> If we don't have (2), for machines of fixed size, in the monolithic setting, would we just overwrite the degree to that of main? What if the fixed columns are defined with the original fixed length, how would we extend them? Does it always work to copy a previous row? With a minimum degree, we get that information from the user.

I think we can assume that fixes columns are specified with any degree above some minimum. They are already specified like this in practice!

So, I think the most pragmatic approach would be to leave everything as is on the language side, but change the linker so that it receives a `dynamic: bool` flag, and then:
- If `dynamic == false`: Set all degrees to `main_degree`, asserting that the machine's degree (if set) was not larger before. So the semantics of the degree changes to a min degree.
- If `dynamic == true`: Don't set any degrees.

So:
- For a monolithic proof, you'd set `dynamic == false` and get all machines in the same size (with some safety assertions, which is better than now!)
- For a "static VADCOP" proof, you'd have to manually set all the size and set `dynamic == true`. But I don't think this is really useful.
- For dynamic VADCOP, you'd set the size of fixed lookups and leave all other sizes set to `None`.
