### ISSUE TITLE
Plonky3 prover: Handle multiple AIRs

### ISSUE THREAD

**Issue by georgwiese** [powdr-labs/powdr#1830]
As an alternative to the Composite Backend, we can implement our own Plonky3 prover (used instead of `unistark`) that is aware of all machines and can prove them in one go.

It should support:
- Shared challenges across machines (i.e., this issue is an alternative to #1608)
- Fixed columns
- Publics
- ...

**Comment by leonardoalt** [comment]
@Schaeff @georgwiese this is done, right?

**Comment by georgwiese** [comment]
Yes
