### ISSUE TITLE
Plonky3 has the ability to break our build

### ISSUE THREAD

**Issue by lvella** [powdr-labs/powdr#1914]
We depend on the main branch of an external repository. If plonky3 changes the API on main (which is changing constantly), our build breaks.

This is serious because it renders our older versions unbuildable. We can't do a `git bisect` across the point where Powdr uses a different Plonky3 interface from the version that is in our local `Cargo.lock`.

**Comment by leonardoalt** [comment]
Wasn't this fixed in the PR?

**Comment by lvella** [comment]
Yes.
