### ISSUE TITLE
Remove the need for `Option` in PolynomialReference::poly_id

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#232]
After the analysis phase, we can assume the poly_id to exist. There could be two different ways to make this work:
1) assign the ID already when the PolynomialReference is created in pil_analizer.
2) make PolynomialReference (and thus the whole analysis AST) generic to allow for the ID to be present or not.

Option 1 is tricky because we still want to maintain compatibility with polygon-hermez pil in the way the IDs are assigned. So we would need two passes: One pass to generate the IDs, the second to build the AST structure.

**Comment by leonardoalt** [comment]
@Schaeff does this still hold after the AST refactoring from last month?
