### ISSUE TITLE
Functions implemented as state machines

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#306]
This can already be done statically such as in https://github.com/powdr-labs/powdr/pull/398. This issue refers to the more general design goals.

We should be able define functions in the high level language as PIL state machines. This way we could e.g. have a high level language function `keccak` that can be called like a regular function and "calls" a keccak state machine.

The problem is that we need to reach down from the high level language across assembly into PIL.

@lvella suggested to just have external functions for this.

Example:

```
extern "C" {
  fn field_mul(a: u64, b: u64) -> u64;
}
pub const field_mul_pil: &str = "
// some PIL code
";
```

Every assembly instruction `call field_mul` is replaced by a custom instruction that is defined through the pil code in the rust source.

One problem is that we need to have certain names available in order to do this properly.

A different approach would be to allow this for lookups only. This means the asm->pil translation would automatically define an instruction for such functions:
```
instr field_mul X, Y -> Z { { X, Y, Z } is 1 { a, b, c} }
```
And then we only define the state machine in the pil code. This would of course profit from the more explicit state machine syntax that defines flags and inputs / outputs, where we then could just write:
```
instr field_mul X, Y -> Z { machine(X, Y, Z) }
```

**Comment by lvella** [comment]
Placing PIL code in strings inside rust doesn't feel right... maybe at least hide it with a macro?

**Comment by chriseth** [comment]
Yes of course, in the end the association between the function and the pil code should be done through a macro. If we can do without a string (I guess this depends on if the tokenizer is compatible with the one by rust), even the better.

**Comment by leonardoalt** [comment]
As an initial implementation we support it now via a static library such as done in https://github.com/powdr-labs/powdr/pull/398

**Comment by leonardoalt** [comment]
A basic version of this is working currently in what we call "coprocessors". I think we should refactor it anyway to be more like syscalls, but I'll open a new issue about it.
