### ISSUE TITLE
Bit constraint solver should be able to solve negative bits

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#327]
The bit constraint solver currently is not able to solve a constraint of the following form:
```
X = -5 + c * 2**32
```
where
```
c is in {0,1 }
X is constrained to 32 bits.
```

It can only solve constraints of the form
`X + Y = <number>`, where `X` and `Y` have non-overlapping bits.

The above constraint is
`X - Y = <number>`
where `number` is negative.

I have the feeling that we should be able to do that as well.

The solution for now is to rewrite the constraint as

```
X = -5 + 2**32 - c * 2**32`
```

**Comment by chriseth** [comment]
Might be fixed by #344

**Comment by leonardoalt** [comment]
@Schaeff @georgwiese do you know if this was indeed fixed?

**Comment by georgwiese** [comment]
Looks like it. Just ran the following test:

```
constant %N = 256;

namespace NegativeBits(%N);

    col fixed L0 = [1] + [0]*;
    col fixed BYTES(i) { i % 256 };
    col witness c, X;

    c * (1 - c) = 0;
    {X} in {BYTES};

    X = -5 + c * 2**8;
```

Figures out that `X = 0xfb` and `c = 1`
