### ISSUE TITLE
Powdr2

### ISSUE THREAD

**Issue by leonardoalt** [powdr-labs/powdr#348]
New assembly structure containing:

- machines
- instructions
- program

Should be recursion oriented.

Tasks:

- [x] https://github.com/powdr-labs/powdr/issues/428
- [x] https://github.com/powdr-labs/powdr/issues/429
- [x] https://github.com/powdr-labs/powdr/issues/430
- [x] https://github.com/powdr-labs/powdr/issues/431

**Comment by leonardoalt** [comment]
I guess we can close this issue and open another one more specific to PIL2? Closing for now, please re-open if needed.

**Comment by chriseth** [comment]
Nice!
