### ISSUE TITLE
Parser cannot parse namespaced names

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#367]
The parser is not able to parse namespaced names inside expressions (inside function bodies for example).

Example:
```
namespace Assembly(2);
    col fixed A = [0]*;
    col fixed C(i) { Assembly.A(i) };
    col witness w;
    
    w = C;
```

This fails to parse `Assembly.A` properly.

**Comment by emilyaherbert** [comment]
@chriseth this isn't just a limitation of parsing but also the AST:
https://github.com/powdr-org/powdr/blob/5d14f71e5389c699403c4e2c5625ac6c29cfd377/ast/src/parsed/asm.rs#L94

Do we want to allow for the use of `String` and any `PolynomialReference`? like:
https://github.com/powdr-org/powdr/blob/5d14f71e5389c699403c4e2c5625ac6c29cfd377/ast/src/parsed/mod.rs#L71

(`Assembly.A` in this example is parsed to `PolynomialReference` here):
https://github.com/powdr-org/powdr/blob/5d14f71e5389c699403c4e2c5625ac6c29cfd377/parser/src/powdr.lalrpop#L367

**Comment by chriseth** [comment]
Yes, I think the proper way would be to replace the whole `PolynomialReference` construct by a combination of Path, IndexAccess and a Next unary operator.

The Analyzed AST can then combine it again into a single construct.
