### ISSUE TITLE
Function inputs and outputs in the single machine case

### ISSUE THREAD

**Issue by Schaeff** [powdr-labs/powdr#379]
#377 introduces functions but restricts them to not having inputs or outputs.

We implement this in the special case of a single machine with a single main function

The design is the following:
```
function main(x: field, y: field) -> field {
   return x + y;
}
```

Under the hood, what this does:
- introduce internal witness columns `_input_0, _input_1, ...` and `_output_0`
- currently restrict to a single field output. Implementing multi-return is not great in my opinion and we should instead have complex types eventually.
- make both inputs and outputs constant within the whole execution trace: `_input_0 = _input_0'` etc
- introduce a special `return` keyword which binds its argument to the output on that line: `instr_return * (x + y - _output_0)`
- expose the inputs and outputs on the first row as public inputs

**Comment by leonardoalt** [comment]
I think this was done? Please reopen if I'm wrong.
