### ISSUE TITLE
Using constants in constraints fails

### ISSUE THREAD

**Issue by georgwiese** [powdr-labs/powdr#397]
If I do something like:

```
pol commit foo;
constant %bar = 3;
foo = %bar;
```

this fails with:
`thread 'main' panicked at 'no entry found for key', /root/powdr/pil_analyzer/src/json_exporter/mod.rs:226:25`

**Comment by chriseth** [comment]
Did you try `foo = bar;`?

**Comment by georgwiese** [comment]
Yes, gives me `thread 'main' panicked at 'Column main.bar not found.', /root/powdr/pil_analyzer/src/pil_analyzer.rs:79:36`. Which makes sense, actually!

I looked into it quickly with Thibaut and I think I can fix it. I assigned myself the issue and will propose a fix later today!
