### ISSUE TITLE
Support sub-sub-machines

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#409]
We should support lookups to machines inside machines.

1. Make the lookup structure detection in "extract machines" more flexible:

Generate a DAG in the following way: All lookups are directed edges. The nodes contain witness column and start with the witness columns in the LHS / RHS of the lookup. Extend the set of witness columns in each node to all witness column that are connected to the other witness column via regular polynomial constraints (i.e. no lookups). We already have some helper functions for that. If one witness column ends up in multiple nodes, join those nodes into a single one.

If the resulting structure is not a DAG with a single root node, we fail. At some point, we could maybe do with multiple root nodes, but I would not support that for now if it is complicated.

2. The set of other machines (or maybe just the direct sub machines?) needs to be passed to the `process_plookup` function in the Machine trait. Maybe we could also store the sub-machines at the point where we construct the machine, but this could prove difficult since if it is an actual DAG (and not a tree), we would have two or more mutable references to a sub-machine stored somewhere.

The issue with the mutable references to the sub machines is also an annoying one. Maybe we could get rid of that by something like a append-only data structure: We don't need full mutating access to the newly generated row, it might be sufficient to just output the new rows somewhere instead of storing it....

**Comment by georgwiese** [comment]
We made some progress here, machines can call each other as long as there are no cycles in the call graph. If there were, we'd fail at runtime, because there would be no machine left to answer the call. It doesn't work exactly as described in this issue though.

**Comment by leonardoalt** [comment]
I think this is done. I'm closing for now, please reopen if I'm wrong.

**Comment by georgwiese** [comment]
I think my comment above is still up-to-date. Probably good enough, not sure if there is use-case for cyclic call graphs.
