### ISSUE TITLE
Witgen: handle hard errors in block machine / sub machines properly

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#411]
Currently, fatal errors in the block machine (and maybe also other machines) are ignored as long as it is able to derive a value for all input columns. Instead, fatal errors are always fatal and should be reported back to the query caller directly.

Note that the way we do witness generation is that we only assign values as long as the assignment is unique / forced. So we don't do any backtracking. This means that when we encounter a contradiction, it is always a fatal error that should stop witness generation.

**Comment by georgwiese** [comment]
This should be fixed.
