### ISSUE TITLE
Implement missing RISCV instructions

### ISSUE THREAD

**Issue by leonardoalt** [powdr-labs/powdr#438]
Considering we target RISC-V 32-bits with extensions `A` and `M`, these are the (pseudo)instructions that are feasible to implement current Powdr approach:

- RV32I (basic) set
  - [x] `lui`
  - [x] `jal`
  - [x] `beq`
  - [x] `bne`
  - [x] `blt`
  - [x] `bge`
  - [x] `bltu`
  - [x] `bgeu`
  - [x] `lb`
  - [x] `lh`
  - [x] `lw`
  - [x] `lbu`
  - [x] `lhu`
  - [x] `sb`
  - [x] `sh`
  - [x] `sw`
  - [x] `addi`
  - [x] `slti`
  - [x] `sltiu`
  - [x] `xori`
  - [x] `ori`
  - [x] `andi`
  - [x] `slli`
  - [x] `srli`
  - [x] `srai`
  - [x] `add`
  - [x] `sub`
  - [x] `sll`
  - [x] `slt`
  - [x] `sltu`
  - [x] `xor`
  - [x] `srl`
  - [ ] `sra`
  - [x] `or`
  - [x] `and`
  - [x] `fence`
  - [x] `fence.i`
  - [x] `ecall`
  - [x] `ebreak` (not exactly the intended behavior)
- RV32M (multiplication) set
  - [x] `mul`
  - [x] `mulh`
  - [x] `mulhsu`
  - [x] `mulhu`
  - [ ] `div`
  - [x] `divu`
  - [ ] `rem`
  - [x] `remu`
- RV32A (atomic) set
  - [x] `lr.w`
  - [x] `sc.w`
  - [ ] `amoswap.w`
  - [x] `amoadd.w`
  - [ ] `amoxor.w`
  - [ ] `amoand.w`
  - [ ] `amoor.w`
  - [ ] `amomin.w`
  - [ ] `amomax.w`
  - [ ] `amominu.w`
  - [ ] `amomaxu.w`
- Pseudoinstructions:
  - [x] `la`
  - [x] `lb`
  - [x] `lh`
  - [x] `lw`
  - [x] `sb`
  - [x] `sh`
  - [x] `sw`
  - [x] `nop`
  - [x] `li`
  - [x] `mv`
  - [x] `not`
  - [x] `neg`
  - [x] `seqz`
  - [x] `snez`
  - [ ] `sltz`
  - [x] `sgtz`
  - [x] `beqz`
  - [x] `bnez`
  - [x] `blez`
  - [x] `bgez`
  - [x] `bltz`
  - [x] `bgtz`
  - [ ] `bgt`
  - [ ] `ble`
  - [ ] `bgtu`
  - [ ] `bleu`
  - [x] `j`
  - [x] `jal`
  - [x] `jr`
  - [x] `jalr`
  - [x] `ret`
  - [x] `call`
  - [x] `tail`
  - [x] `fence`
  - [ ] `add` (undocumented, alias for `addi`)

Instructions that we do not support because we treat labels in code as opaque values, and we don't support user computations over code addresses nor PC relative addresses.

- RV32I (basic) set
  - `auipc`
  - `jalr` (the restricted `jalr` pseudoinstruction is supported, though, because the argument used as PC offset is zeroed)
- Pseudoinstruction:
  - `lla` (undocumented, like `la` but for labels close to the PC)

Instructions we do not support because we only care about unprivileged code and do not maintain timers nor control, status and counter registers:

- RV32I (basic) set
  - `csrrw`
  - `csrrs`
  - `csrrc`
  - `csrrwi`
  - `csrrsi`
  - `csrrci`

**Comment by emilyaherbert** [comment]
Some to add to the list:
- SRA: arithmetic shift right
- FENCE: "order device I/O and memory accesses as viewed by other RISC-V harts and external devices or coprocessors"
- AUIPC: add upper immediate to pc
