### ISSUE TITLE
Support bits as block machine `function_id`

### ISSUE THREAD

**Issue by Schaeff** [powdr-labs/powdr#452]
Suggested here https://github.com/powdr-labs/powdr/pull/383#discussion_r1274935492

I suspect this should be implemented on top of the basic `function_id` we have now, ideally in the language.

**Comment by leonardoalt** [comment]
@georgwiese did you do something like this recently? As part of the permutation stuff?

**Comment by georgwiese** [comment]
This can be worked around by defining an intermediate polynomial like `let operation_id = is_op1 + 2 * is_op2 + 4 * is_op3 ...`.

That's already done in the arithmetic machine, for example. This works in all practical use-cases I'm aware of. In theory it could happen that the number of bits is too large for the field.

**Comment by leonardoalt** [comment]
I'll close this then.
