### ISSUE TITLE
Run pilopt after linking, not before execution

### ISSUE THREAD

**Issue by Schaeff** [powdr-labs/powdr#468]
We create a PIL file at the end compilation, but then during execution optimise it and run on that. Why not instead optimise at the end of compilation?

**Comment by ShivangRawat30** [comment]
Hey I am currently learning rust, as it is a good first issue can you please assign this to me

**Comment by Schaeff** [comment]
I misunderstood our pipeline here, pilopt happens on PIL, which makes sense. I got confused because at the moment we don't separate compiling and running. Closing but @ShivangRawat30 watch this space we'll try to add more first issues!
