### ISSUE TITLE
Implement halo2 integration without plaf, only with PIL

### ISSUE THREAD

**Issue by Schaeff** [powdr-labs/powdr#472]
In the interest of making the backend integration as thin as possible, implement the halo2 integration entirely in PIL.
Two things need to happen:
- implement the wrapper in PIL (increase the degree and introduce the 2 selectors). This could be done independently of the second item.
- implement the Halo2 constraint system trait for PIL (similar to [how plaf itself implements it](https://github.com/Dhole/polyexen/blob/5f1eebd773e0e2ae82b1c8dc15d68f422b87c6e5/src/plaf/backends/halo2.rs#L158))

Then the former of these two could be moved out of the backend as a `machine Halo2Wrapper`, so that the integration is even thinner.

Note: this is not adding any new functionality, but it would begin to inform what is required for the aggregation strategy.

**Comment by leonardoalt** [comment]
Done recently!
