### ISSUE TITLE
Simple type system

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#523]
Add some basic type system. Brainstorming: https://hackmd.io/spOJ7hDXR6O50dxyp9dPvw?edit

We could start with the following types:

```
bool
int
fe
A[]
A -> B
tuples
```

Related: #338

**Comment by chriseth** [comment]
Some more brainstorming from the office:

We do not distinguish between fixed polynomials and witness polynomials.
Everything (constants, witness polys, fixed polys, macros) is declared simply declared / defined using `let`:
```
let constant = 7;
let witness_column;
let fixed_column = |i| { i % 7 };
let my_macro = |x| { (x + 1) * iszero }; // functions (closures!) can reference outside declarations
```

Operators:
`'` is an operator with signature `(int -> fe) -> (int -> fe)` and can always be used (we will figure out how to translate to pil json). It might be overloaded on arrays.
`=` is an operator that returns `cosntr` (a constraint). This means it can only be used in contexts where constraints are allowed, or in functions that return constraints ("macros"!).
`==` is an operator that returns `bool`

There is a standard library that deals with the translation of "higher level constructs" like `==`, `if`, `match` to low-level constraints. This is done using "macros" (which are probably marked by special comments):

```
#[lang = "eq"]
let op_eq= constr |x: int -> fe, y: int -> fe|: int -> fe
   is_zero(x - y);

let is_zero = constr |x: int -> fe|: int-> fe {
  let x_inv;
  let x_is_zero;
  constr (1 - x_is_zero)*(x_inv * x - 1) = 0;
  constr (x_is_zero) * (1 - x_is_zero) = 0;
  x_is_zero
};
```

What happens here is that we introduce special functions called `constr` functions: They are functions where we are allowed to declare (witness) column and where we can generate new constraints. The witness columns have names that are local to the function (and do not need to be unique). If we call such a function multiple times, it might generate "copies" of the constraints. The generated columns and constraints are not formal return values of the functions.

Because we want the language to be declarative and functional, calling the same such function multiple times on the "same" input should yield the "same" output.
Example:
```
let foo = constr ||: int-> fe { let n; n }
foo() = 7;
foo() = 8;
```

Here, we define a function that returns an unconstrained witness column. The desire is that the constraint system `foo() = 7; foo() = 8;` should be unsatisfiable, because in a declarative functional language, `foo()` is a constant that can not be equal to 7 and 8 at the same time. So the semantics would be that the witness column returned by `foo` is the same in both calls.

On the other hand, it is difficult to determine (in the general case) if `bar(x)` and `bar(y)` are called on the same input and thus should return the same witness columns or fresh ones.

The "simple" solution to this problem is to determine if the return value of the function deterministically depends on the input value. In this case, it is safe to always return a fresh copy and rely on an optimizer to remove identical columns and constraints (maybe early on during generation phase). Most macros will just return an expression of the input, which usually satisfies this property. In the case of `is_zero`, we can use a pattern matcher to determine that `x_is_zero` deterministically depends on the input. Note that it is not a problem that `x_inv` is unconstrained in the case where `x` is zero, because it does not appear in the return value.


Of course we do not want to have that translation being performed inside fixed polynomial definitions that handle concrete values, but instead only in constraints with witness columns.
One idea is to do the translation only if the `==` operator is used on `int -> fe` (i.e. whole columns) and thus make the type system handle this distinction. The idea is that inside fixed column definitions, you typically operator on `fe` instead of whole columns.

**Comment by chriseth** [comment]
If we want to get rid of macros altogether, we also need function that return lookups (and other connection identities). I would say, lookups are just the result of a special operator `{ ... } in { ... }` - maybe we can define its components specially, but I guess we don't need to for now. The result type of the operator is a `constr`, the same as the type of the `=` operator.

In order to use the type checker and similar things also in assembly, it needs to be flexible enough:
We need a name resolution and type checking component that can do its work also embedded inside the assembly part of the code.

**Comment by chriseth** [comment]
For fixed columns we currently use arrays and iterated arrays and concatenation of arrays. These operators could be defined as follows:
```
// * applied to a finite array yields a function
let op_star = |x: fe[]|: int -> fe |i: int| x[i % x.len()]
// finite array plus finite array extends the array
let op_plus = |l: fe[], r: fe[]|: fe[] // not sure how to write array concatenation without using plus...
// finite array plus function prepends the array to the function - this is how it works for arrays,but should it also work like that for functions?
let op_plus_fin_fun = |l: fe[], r: int -> fe|: int -> fe |i: int| if i < l.len() { l[i] } else { r(i - i.len()) };
```

We still need a way to do operator overloading without function overloading. i.e. we need some kind of simplistic `impl` or system. We could also just use specific markers and not rely on the names at all.

**Comment by chriseth** [comment]
If we want to declare an array of witnesses with the `let` syntax, it is quite tedious to use:
```
let x: (int -> fe)[8];
```

We could introduce the type `col` as an alias for `int -> fe`:
```
let x: col[8];
```

**Comment by leonardoalt** [comment]
@chriseth I guess this is done?
