### ISSUE TITLE
Require `latch` and `operation_id` only if a machine has operations

### ISSUE THREAD

**Issue by Schaeff** [powdr-labs/powdr#577]
The concept of latch for a machine is linked to being able to call it from the outside. If a machine has no operations, then it cannot be called. This is still useful for completeness, so that we can write a machine entirely in powdr-PIL. We should allow:

```
machine Machine {
   constraints {
   }
}
```

While #576 can be seen as inference, we cannot infer a latch if there are no operations. This suggests the latch should be made optional in the machine abstraction. So
- we check that a machine has no `(latch, operation_id)` iff it has no operations
- when instantiating the links, we know from type checking that the target machine must have a `(latch, operation_id)` (as the link targets an operation)

**Comment by Schaeff** [comment]
We should probably fix #576 before this.

**Comment by leonardoalt** [comment]
@georgwiese I think this was done, right?

**Comment by georgwiese** [comment]
Yes!
