### ISSUE TITLE
Implement data section as single continuous array.

### ISSUE THREAD

**Issue by lvella** [powdr-labs/powdr#582]
Where labels are indexes into the data array, so that declarations such as bellow will work:

```asm
tdat:
tdat1:  .half 0x00ff
tdat2:  .half 0xff00
tdat3:  .half 0x0ff0
tdat4:  .half 0xf00f
```

as used in the official RISC-V tests for instructions `lh` and `lhu`.

**Comment by leonardoalt** [comment]
This already works. A few caveats here are:

1. Unreferenced labels are completely removed, together with the data they point to. This may cause problems if the assembly program references data in an unsafe way, for example accessing `tdat1` via `tdat2 - 2`.
2. Currently we spend a full word of powdr-asm memory per directive, regardless if it's a full word or a byte.
3. The only thing missing in the example you gave is `.half` itself. I have a local implementation and will open a PR this week.

**Comment by leonardoalt** [comment]
This is done, and we have https://github.com/powdr-labs/powdr/issues/581 tracking the `.half` directive
