### ISSUE TITLE
`ColumnMap`: Only store subset of columns

### ISSUE THREAD

**Issue by georgwiese** [powdr-labs/powdr#605]
In Witgen code, a `ColumnMap<V>` wraps a `Vec<V>`. It simulates a map with a `PolyID` key by using `poly_id.id` as the index. This works because polynomial IDs of polynomials of a given type are consecutive and is faster than using a `BTreeMap` or `HashMap`.

In machines, we then typically store rows as `ColumnMap<Cell<T>>`, which means that this reserves an entry for *all* columns, not just the ones actually used by the machine. This leads to higher memory usage than necessary.

We could instead reassign polynomial IDs such that columns of a machine are consecutive. Then, storing a simple offset with the `ColumnMap` would allow us to decrease the size of the array.

**Comment by leonardoalt** [comment]
@georgwiese is this still relevant?

**Comment by georgwiese** [comment]
The issue is not fixed, but I think after #726 it's not really important. We use `ColumnMap` only in the non-finalized rows. The finalized rows only store the cells that are actually part of the machine. Most rows should be finalized during long computations.
