### ISSUE TITLE
Pieces needed to support native Poseidon calls from Rust

### ISSUE THREAD

**Issue by georgwiese** [powdr-labs/powdr#607]
There have been efforts to support calling a "native" Poseidon machine from Rust code. The basic integration works (see #495 and #534), but there are a few features missing to make this work fully.

### 1. Implement Poseidon SM for all supported fields

Current state:
- For BN254, this is implemented
- For Goldilocks, we need multi-returns (#485) in order to return more than one field element (which in Goldilocks is only 64 bit)

### 2. Wrap arbitrary field elements

To convert from the hash (a field element) to something like an `u32` (or an array thereof), we need to do a byte-decomposition of arbitrary field elements. This requires extra work to make sure the prover's decomposition does not overflow, which would be a soundness bug.

Current state:
- A working version for Goldilocks is merged: #570
- The same approach generalizes to other fields, but for BN254, witgen does not find a witness, because it is not smart enough to recognize that there is a unique one.
- Actually, for the same reason, it is surprising that the Goldilocks solution works. In fact, it still does when we remove the part that ensures soundness, which is tracked in #593.

### 3. RISC-V Compiler: Include Poseidon and wrapping machines of the respective field

The main feature we need here is to be able to distinguish which field we're compiling for.

**Comment by leonardoalt** [comment]
This is done
