### ISSUE TITLE
Namespaces and imports for PIL

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#663]
In order to unify powdr-asm and powdr-pil, we need pil statements to be allowed outside machines (declarations only, of course, no constraints) and the namespace mechanism to work properly.

The idea is that we can run PIL reference resolution and type checking (type inference) already on the PIL parts in the assembly code. This way, we can remove the macros by a proper concept. We are also not "running blind" until after machine to pil translation. We would do PIL reference resolution again on the PIL translated from ASM, but it might even be optional.

We should probably change the current namespace separator from `.` to `::` in the same way it is done in many languages: `A::B` is a namespace access, which means it can be resolved before type checking and `A` is the name of a module or a type, not a variable, while `A.B` is a member access, which can only be resolved once the type of `A` is clear and `A` is a variable.

Here is some example code that does not even make use of `use` or namespace access, since I think that is kind of clear.

```
let difference_to_next = |x| x' - x;
let every_k = |k| (|i| if i % k == 0 { 1 } else { 0 });

machine SimpleStatic(latch, operation_id) {
        degree 8;

        operation power_4<0> x -> y;

        col fixed operation_id = [0]*;
        let latch = every_k(4);

        let x;
        let y;

        (1 - latch) * difference_to_next(x) = 0;
}
```

The bigger problem is how we translate the machine to PIL.

If I understand the machine module system correctly, the machine does not create a namespace, it just creates a scope. This is totally fine when you parse the example above and resolve PIL references.

It is a also kind clear what happens to `difference_to_next` and `every_k`: Nothing.

The big open question is what happens to `x` and `y` when we instantiate SimpleStatic. We could create a PIL namespace (more the abstract concept than the existing syntactical concept we already have) - then it might work, but I don't really understand the machine instantiation concept yet well enough to judge.

**Comment by chriseth** [comment]
Illustrate what? Function declarations are still pil statements. I still don't fully see how the pil namespaces work with asm machine instances, but maybe we can discuss this IRL at some point.

**Comment by Schaeff** [comment]
In the module system, symbols are machines or modules. We can add a new type of symbol for PIL functions and make your example work. Or is there something preventing that in your opinion?

**Comment by Schaeff** [comment]
So I think I see what you mean: basically how do you "remove" the machine. If you just remove it, you may have an `x` in two different machines which would end up colliding.

The general intuition I ended up with last time we talked about this is that we should not "translate the machine to PIL". We should instead keep the machine tree all the way down. I do not have a complete plan yet though.

**Comment by chriseth** [comment]
Ah, so machines are actually namespaces? That's actually much better!

But it's a bit inconsistent because modules do not import the super namespace by default but machines do, right?

**Comment by Schaeff** [comment]
> Ah, so machines are actually namespaces? That's actually much better!

No, they are not. By "we use PIL namespaces" I mean that each machine instance ends up in a different PIL namespace in the final PIL, see [here](https://github.com/powdr-labs/powdr/tree/main/analysis#linker).

**Comment by chriseth** [comment]
I was referring to "symbols are machines or modules". So in the end machines are more like functions, right? They create their own scope but are not a namespace and all the symbols from the namespace the machine is defined in, are available inside the machine.

And this is the problematic part: If we want pil namespaces to behave like powdr modules, then the symbols outside of the namespace are not automatically visible inside the namespace, unless you import them. So we cannot just use a pil namespace for a powdr machine. We could add a `use super:*` at the beginning, though.

**Comment by chriseth** [comment]
Implemented in https://github.com/powdr-labs/powdr/pull/821
