### ISSUE TITLE
Overflow vulnerability in `mul` instruction in Goldilocks field

### ISSUE THREAD

**Issue by georgwiese** [powdr-labs/powdr#713]
In our RISC-V machine, we use the following constraints to implement multiplication:

```
    // Multiply two 32-bits unsigned, return the upper and lower unsigned 32-bit
    // halves of the result.
    // X is the lower half (least significant bits)
    // Y is the higher half (most significant bits)
    instr mul Z, W -> X, Y {
        Z * W = X + Y * 2**32,
        X = X_b1 + X_b2 * 0x100 + X_b3 * 0x10000 + X_b4 * 0x1000000,
        Y = Y_b5 + Y_b6 * 0x100 + Y_b7 * 0x10000 + Y_b8 * 0x1000000
    }
```

where ``X_b1, ..., X_b4, Y_b5, ... Y_b8` are range-constrained to be bytes.

The problem is that the right-hand side of the first equation can overflow in the Goldilocks field (where $p = 2^{64} - 2^{32} + 1$ = `0xffffffff00000001`).

For example, to prove the lower half of `1 * 1 = 2`, set `Y = 0xffffffff` and `X=0x00000002`. With these values, the right-hand side of the first constraint will evaluate to 1:

`X + Y * 2**32 = 0xffffffff00000002 = p + 1 = 1`

Both `X` and `Y` can be decomposed into 4 bytes, so constraints 2 & 3 will very as well.

Note that this is not a problem on the larger BN254 field. On the Goldilocks field, this could be fixed by using the `SplitGL` machine from the standard library.

**Comment by leonardoalt** [comment]
We should really fix this.
