### ISSUE TITLE
`lrsc` test is broken

### ISSUE THREAD

**Issue by lvella** [powdr-labs/powdr#760]
It is broken at least since 1c5b64bd26d4e99635d4adf3952dd7c9acee303d, as far as I have tested. Maybe the instructions are broken, too.

**Comment by leonardoalt** [comment]
That commit cant have broken it, it only moved some functions around

**Comment by lvella** [comment]
> That commit cant have broken it, it only moved some functions around

But that is the oldest I have tested and it was already broken.

**Comment by lvella** [comment]
Yes, it is fixed.
