### ISSUE TITLE
Does it support Halo2? 

### ISSUE THREAD

**Issue by skardas** [powdr-labs/powdr#828]
I did not see any option for arguments.

` powdr pil helloworld.asm --field bn254 --force --inputs 0 --prove-with halo2        
error: invalid value 'halo2' for '--prove-with <PROVE_WITH>'
  [possible values: estark, pil-stark-cli]`

**Comment by leonardoalt** [comment]
The halo2 prover is opt-in via the `halo2` feature. You need to compile powdr with `--all-features` or specifically the halo2 feature for it to be enabled in the final binary.

**Comment by leonardoalt** [comment]
Closing the issue, please reopen if needed
