### ISSUE TITLE
Can we implement memory as a Powdr machine?

### ISSUE THREAD

**Issue by georgwiese** [powdr-labs/powdr#844]
I tried rewriting the write-once memory as a Powdr machine:
```
machine Main {

    degree 256;

    WriteOnceMemory memory;

    reg pc[@pc];
    reg X[<=];
    reg Y[<=];
    reg A;


    instr mload X -> Y = memory.access
    instr mstore X, Y -> = memory.access

    instr assert_eq X, Y { X = Y }

    function main {
        mstore(17, 42);
        A <== mload(17);
        assert_eq A, 42;

        return;
    }
}

machine WriteOnceMemory {

    operation access ADDR -> v;

    let ADDR = |i| i;
    let v;
}
```

These are all the errors:
- This currently fails with: `Machine  should have a latch column as it does not have a pc and has operations`
- Even if I add a latch with `let latch = |i| 1;`, it complains about `mstore` having the wrong signature. I could add more operations, but then I would need an operation ID? 
- Even if I remove mstore, witgen does not detect the machine as `WriteOnceMemory` because it has a latch.
- If I fix that, it works!

I think these are symptoms of the abstraction not really working out for this use-case, so it could be a good case study for improving them!

**Comment by leonardoalt** [comment]
Maybe done in https://github.com/powdr-labs/powdr/pull/1129 ?

**Comment by georgwiese** [comment]
No, I just tried and it looks like all of the issues above are still there.
