### ISSUE TITLE
powdr-pil implementation of 256-bit bitwise and arithmetic operations

### ISSUE THREAD

**Issue by leonardoalt** [powdr-labs/powdr#908]
Ref https://github.com/0xPolygonHermez/zkevm-proverjs/blob/main/pil/binary.pil
Ref https://github.com/powdr-labs/powdr/blob/main/std/binary.asm

Should be added to the stdlib.

**Comment by vuvoth** [comment]
Can I work on this issue?

**Comment by leonardoalt** [comment]
This is actually easier to do directly in asm or Rust.

Closing as won't do.
