### ISSUE TITLE
Documentation: Example of proof verification?

### ISSUE THREAD

**Issue by matthiasgeihs** [powdr-labs/powdr#917]
Hey! I was going through the documentation and specifically the hello world example. The examples explain how to generate proofs, but they don't touch on how to verify them.

- Is proof verification done with `powdr`?
- If not, how would proofs be verified?

**Comment by leonardoalt** [comment]
Hey! Currently we rely on the proof libraries themselves for proof verification. Though I do agree that our CLI and library should also provide entry points for that. We're tracking the former here https://github.com/powdr-labs/powdr/issues/890 and it should be done soon

**Comment by matthiasgeihs** [comment]
At least it would be helpful to have that covered in the documentation (e.g., show how to verify the example program using one of the supported proof libraries). This would make it much easier for a beginner to understand the full picture.
