### ISSUE TITLE
Parser: parse literal numbers as unlimited precision integers

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#947]
The parser parses literal numbers as field elements. This means that the behaviour of the parser depends on the chosen field.
Since we have integer types now, it would be much more natural to parse literal numbers as unlimited size integers (they are converted to those in the evaluator). Interestingly, this would also remove the template parameter `T` from the ast.

A preliminary investigation showed that this creates problems in the asm to pil conversion. Maybe we should inject explicit conversions to field elements at least in the instruction/assignment lines.

**Comment by chriseth** [comment]
If this is done, most of the workarounds in https://github.com/powdr-labs/powdr/pull/953 should be reverted.

**Comment by leonardoalt** [comment]
@chriseth this was done recently, right?

**Comment by chriseth** [comment]
Done in #919
