### ISSUE TITLE
Expression Display: Reduce the number of parentheses

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#962]
The Display trait for Expression adds parentheses in order to ensure correct parsing order. These are not always necessary. The Display traits for TypeName and Type have an example how parentheses can be avoided: They have to be added by the display method of the outer element which needs to ask the inner element if parentheses are needed to parse it ambiguously. Due to operator precedence, this could be a bit more tricky, but we could supply the current precedence in the `needs_parentheses` call. In any case, even removing some parentheses would help already.

Here is a description of the general procedure: https://stackoverflow.com/questions/6277747/pretty-print-expression-with-as-few-parentheses-as-possible

**Comment by aminlatifi** [comment]
@chriseth @leonardoalt It would be my pleasure to contribute to this project,
As I look into `ast/src/parsed/display.rs` file, particularly to `format_type_with_parentheses` function, the parenthesis generation can be skipped simply by not calling this function and just passing the value itself.

(https://github.com/powdr-labs/powdr/blob/3f771638467a8bd527805239ac614dd56e65f11c/ast/src/parsed/display.rs#L737-L743)

Actually, the `needs_parentheses` function is only called in `format_type_with_parentheses` method, and there is no complex process. 
If you agree I can decommission `format_type_with_parentheses` in places where no parenthesis is needed (like a list of types? or enum variant?!)

Please let me know if I am mistaken about anything. Furthermore, can you guide me to produce examples in which extra parentheses are generated? I am new to powdr.

**Comment by aminlatifi** [comment]
I made #1270. I tried to be in accord with @chriseth guidance.
I appreciate it if one of you could do the review.

**Comment by leonardoalt** [comment]
Was this implemented in https://github.com/powdr-labs/powdr/pull/1289 ?

**Comment by chriseth** [comment]
Pretty much, yes. I think there is still something left at the higher level, but I think we can close this.
